left_arm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - left_arm_0_joint
      - left_arm_1_joint
      - left_arm_2_joint
      - left_arm_3_joint
      - left_arm_4_joint
      - left_arm_5_joint
      - left_arm_6_joint
      
  # computed_torque_controller
  ComputedTorqueController:
    type: lwr_controllers/ComputedTorqueController
    root_name: left_arm_base_link
    tip_name: left_arm_7_link      
  # VS computed_torque_controller
  VSComputedTorqueController:
    type: lwr_controllers/VSComputedTorqueController
    root_name: left_arm_base_link
    tip_name: left_arm_7_link   
    
         #    Joint Impedance Controllers
  JointImpedanceController:
    type: lwr_controllers/JointImpedanceController
    root_name: left_arm_base_link
    tip_name: left_arm_7_link 
    stiffness_gains: 300
    damping_gains: .7     
    
     #   VS Joint Impedance Controllers LUCA GEMMA
  VSJointImpedanceController:
    type: lwr_controllers/VSJointImpedanceController
    root_name: left_arm_base_link
    tip_name: left_arm_7_link 
    stiffness_gains: 300
    damping_gains: .7  
    
    ## Inverse Dynamics Controllers
  #InverseDynamicsControl:
    #type: lwr_controllers/InverseDynamicsController
    #root_name: vito_anchor
    #tip_name: left_arm_7_link


left_ft_sensor:
 force_torque_sensor_controller:
   type: force_torque_sensor_controller/ForceTorqueSensorController
   publish_rate: 1000
   resources:
   - left_measure_joint  

left_hand:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - left_hand_synergy_joint

right_arm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - right_arm_0_joint
      - right_arm_1_joint
      - right_arm_2_joint
      - right_arm_3_joint
      - right_arm_4_joint
      - right_arm_5_joint
      - right_arm_6_joint
      
    #  computed_torque_controller
  ComputedTorqueController:
    type: lwr_controllers/ComputedTorqueController
    root_name: right_arm_base_link
    tip_name: right_arm_7_link  
     # VS computed_torque_controller
  VSComputedTorqueController:
    type: lwr_controllers/VSComputedTorqueController
    root_name: right_arm_base_link
    tip_name: right_arm_7_link   
    
       #    Joint Impedance Controllers
  JointImpedanceController:
    type: lwr_controllers/JointImpedanceController
    root_name: right_arm_base_link
    tip_name: right_arm_7_link 
    stiffness_gains: 300
    damping_gains: .7    
     #   VS Joint Impedance Controllers LUCA GEMMA
  VSJointImpedanceController:
    type: lwr_controllers/VSJointImpedanceController
    root_name: right_arm_base_link
    tip_name: right_arm_7_link 
    stiffness_gains: 300
    damping_gains: .7  
    
  ## Inverse Dynamics Controllers
  #InverseDynamicsControl:
    #type: lwr_controllers/InverseDynamicsController
    #root_name: vito_anchor
    #tip_name: right_arm_7_link   

right_ft_sensor:
 force_torque_sensor_controller:
   type: force_torque_sensor_controller/ForceTorqueSensorController
   publish_rate: 1000    
   resources:
    - right_measure_joint  

right_hand:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - right_hand_synergy_joint

head:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - head_neck_pitch_joint
      - head_neck_roll_joint
      - head_neck_yaw_joint
      - head_head_tilt_joint
      - head_eyes_tilt_joint
      - head_left_eye_joint
      - head_right_eye_joint


